apiVersion : apps/v1
kind: Deployment
metadata:
  name: commentapi 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commentapi
  template:
    metadata:
      labels:
        app: commentapi 
    spec:
      containers:
        - name: commentapi 
          image: acrvod.azurecr.io/commentapi
          ports:
          - containerPort: 80